# Generated by Django 6.0.4 on 2026-05-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0015_feedbackform_feedbackresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='form',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackForm',
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
